### ISSUE TITLE
panicked

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/fontc#479]
I get this when I compile one of my file:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: EMITTER, problem: "expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS" }', fontir/src/ir.rs:1099:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-10-02T18:41:59.835228Z main fontc::workload ERROR] Fe(Glyph(cent)) failed Job panicked: 'called `Result::unwrap()` on an `Err` value: Error { kind: EMITTER, problem: "expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS" }'
At least one work item failed
```
This is one of my fonts. I can provide the file if needed but not over git.

**Comment by schriftgestalt** [comment]
I thought I can make a simplified test file. The error message says something about "cent". So I removed all other glyphs but the cent. But that produces this:
```
[2023-10-02T18:54:26.959176Z main fontc::workload ERROR] Be(GlyfFragment(cent)) failed 'cent' has interpolation-incompatible paths
At least one work item failed
```
This is because the glyphs has bracket layers.
[bracketLayer.glyphs.zip](https://github.com/googlefonts/fontc/files/12785712/bracketLayer.glyphs.zip)

**Comment by cmyr** [comment]
can you get a backtrace? You can enable backtraces by setting `RUST_BACKTRACE=1` before whatever command you were running to invoke fontc.

**Comment by schriftgestalt** [comment]
How do I set this?

**Comment by rsheeter** [comment]
```shell
$ export RUST_BACKTRACE=1
$ echo $RUST_BACKTRACE
1
$ fontc ...args to fontc...
```

**Comment by rsheeter** [comment]
We don't support sparse glyphs from .glyphs yet, #62. We should fix that :) It would still be helpful to have a stack trace with the full font, the original error with Fe(Glyph(cent)) seems like it might be something else.

**Comment by schriftgestalt** [comment]
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: EMITTER, problem: "expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS" }', fontir/src/ir.rs:1109:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1076:23
   4: <fontir::ir::GlyphAnchors as fontir::orchestration::Persistable>::write
             at /Users/georg/Code/Stuff/fontc/fontir/src/ir.rs:1109:9
   5: fontir::orchestration::ContextMap<I,T,Ir>::set_unconditionally
             at /Users/georg/Code/Stuff/fontc/fontir/src/orchestration.rs:238:13
   6: fontir::orchestration::ContextMap<I,T,Ir>::set
             at /Users/georg/Code/Stuff/fontc/fontir/src/orchestration.rs:266:9
   7: <glyphs2fontir::source::GlyphIrWork as fontdrasil::orchestration::Work<fontir::orchestration::Context,fontir::orchestration::WorkId,fontir::error::WorkError>>::exec
             at /Users/georg/Code/Stuff/fontc/glyphs2fontir/src/source.rs:789:9
   8: fontc::work::AnyWork::exec
             at /Users/georg/Code/Stuff/fontc/fontc/src/work.rs:101:34
   9: fontc::workload::Workload::exec::{{closure}}::{{closure}}::{{closure}}
             at /Users/georg/Code/Stuff/fontc/fontc/src/workload.rs:326:29
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  11: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  12: ___rust_try
  13: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  14: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  15: fontc::workload::Workload::exec::{{closure}}::{{closure}}
             at /Users/georg/Code/Stuff/fontc/fontc/src/workload.rs:325:44
  16: rayon_core::scope::Scope::spawn::{{closure}}::{{closure}}
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/scope/mod.rs:526:57
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panic/unwind_safe.rs:271:9
  18: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:500:40
  19: ___rust_try
  20: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:464:19
  21: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panic.rs:142:14
  22: rayon_core::unwind::halt_unwinding
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/unwind.rs:17:5
  23: rayon_core::scope::ScopeBase::execute_job_closure
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/scope/mod.rs:689:28
  24: rayon_core::scope::ScopeBase::execute_job
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/scope/mod.rs:679:29
  25: rayon_core::scope::Scope::spawn::{{closure}}
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/scope/mod.rs:526:13
  26: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:169:9
  27: rayon_core::job::JobRef::execute
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/job.rs:64:9
  28: rayon_core::registry::WorkerThread::execute
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:859:9
  29: rayon_core::registry::WorkerThread::wait_until_cold
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:793:21
  30: rayon_core::registry::WorkerThread::wait_until
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:768:13
  31: rayon_core::registry::WorkerThread::wait_until_out_of_work
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:817:9
  32: rayon_core::registry::main_loop
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:922:5
  33: rayon_core::registry::ThreadBuilder::run
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:52:18
  34: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /Users/georg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.12.0/src/registry.rs:97:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-10-04T16:04:18.619241Z main fontc::workload ERROR] Fe(Glyph(cent)) failed Job panicked: 'called `Result::unwrap()` on an `Err` value: Error { kind: EMITTER, problem: "expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS" }'
At least one work item failed
```
