### ISSUE TITLE
--incremental panics "Spawned more jobs than items available to run" when run 2nd time

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc#581]
If you build GS twice with the --incremental flag using the latest fontc main, the second time it panics with the following error:

```
clupo@clupo-macbookpro3 ~/oss/fontc (main)
$ rm -rf build
clupo@clupo-macbookpro3 ~/oss/fontc (main)
$ cargo run -- ../googlesans/source/GoogleSans/GoogleSans.designspace --incremental
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/fontc ../googlesans/source/GoogleSans/GoogleSans.designspace --incremental`
clupo@clupo-macbookpro3 ~/oss/fontc (main)
$ cargo run -- ../googlesans/source/GoogleSans/GoogleSans.designspace --incremental
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/fontc ../googlesans/source/GoogleSans/GoogleSans.designspace --incremental`
thread '<unnamed>thread '' panicked at <unnamed>fontc/src/workload.rs' panicked at :fontc/src/workload.rs372::37229::
29Spawned more jobs than items available to run:

Spawned more jobs than items available to runnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread '<unnamed>' panicked at thread 'fontc/src/workload.rs<unnamed>:' panicked at 372fontc/src/workload.rs::372:29:
thread '29:
Spawned more jobs than items available to runSpawned more jobs than items available to run

thread '<unnamed>' panicked at thread '<unnamed>thread '' panicked at fontc/src/workload.rs<unnamed>fontc/src/workload.rs<unnamed>' panicked at ' panicked at :fontc/src/workload.rsfontc/src/workload.rs:372:::29:
Spawned more jobs than items available to run372
372:372::2929:
:
Spawned more jobs than items available to run29
:
Spawned more jobs than items available to run
Spawned more jobs than items available to run
thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at <unnamed>' panicked at fontc/src/workload.rs:372:29:
fontc/src/workload.rsSpawned more jobs than items available to runthread 'thread '
<unnamed>' panicked at <unnamed>' panicked at thread '' panicked at fontc/src/workload.rs<unnamed>fontc/src/workload.rs::372:29thread ':
' panicked at <unnamed>Spawned more jobs than items available to runfontc/src/workload.rs' panicked at thread '' panicked at
fontc/src/workload.rs:372thread 'fontc/src/workload.rs372:<unnamed>:::' panicked at 372:<unnamed>372thread '29fontc/src/workload.rsfontc/src/workload.rs:372::372::29372' panicked at thread ':fontc/src/workload.rs<unnamed>2929::
<unnamed>Spawned more jobs than items available to run:' panicked at
29fontc/src/workload.rs:
::
29372:
' panicked at :
Spawned more jobs than items available to runSpawned more jobs than items available to runfontc/src/workload.rs:
thread '29Spawned more jobs than items available to run
:372
372Spawned more jobs than items available to run
::
29<unnamed>Spawned more jobs than items available to run:' panicked at
29fontc/src/workload.rs:
Spawned more jobs than items available to runSpawned more jobs than items available to run


:
Spawned more jobs than items available to run
:372:29:29:
Spawned more jobs than items available to run
:
Spawned more jobs than items available to run
```

Not sure what's going on...

Maybe the gsbuild workflow should test both normal build and incremental one (building twice for the latter) /cc @chrissimpkins

**Comment by anthrotype** [comment]
I think I found where the issue is. Some jobs among those "launchable" are skipped and not added to the run_queue because they are up-to-date (`if !job.run ... continue`), but then the following loop attempts to pop one item from the run_queue for each launchable, without taking into account those that were skipped.
I'll send a PR

**Comment by anthrotype** [comment]
It's a bit concerning that the current test suite in `fontc/lib.rs`, which does contain a bunch of tests named `second_compile_*`, did not catch this issue. Only when fontc is run from the command line this panic can be reproduced. It appears as if the fontc tests `compile` method and the actual fontc run() function (that is used when invoking fontc main.rs as executable) do not do exactly the same thing..
